### ISSUE TITLE
Not able to save settings

### ISSUE THREAD

**Issue by bentalexanderhaase** [Antergos/nodebb-plugin-sso-auth0#1]
After installing this plugin and restarting NodeBB I went onto `Social Authentication` >> `Auth0`.

In there I inserted all details for the app (creted before) which I got from the auth0.com website.

Upon clicking on "save" nothing happens, when leaving the page and reopening it, all settings are gone.

Only guess is that under it says `http://localhost:4567/auth/auth0/callback` which I entered exactly like this on the auth0.com which to me makes no sense because of `localhost`. 

Running latest NodeBB v0.9.4 behind NGINX reverse proxy.

**Comment by lots0logs** [comment]
There was a change in NodeBB recently regarding relative and absolute URLs for the site when accessed by plugins. I just havent had a chance to look at it and make the necessary changes. I will take care of it later tonight though. Sorry about that!

**Comment by bentalexanderhaase** [comment]
@lots0logs no worries, thanks for the fast reply!

**Comment by lots0logs** [comment]
@ET-Bent Is your NodeBB install otherwise working properly? Did you run the first-run setup wizard from command line? It asks you for your forum's web address. You should **not** put `localhost` there. Could you post the non-sensitive parts of your `config.json` here please? Thanks.

**Comment by bentalexanderhaase** [comment]
@lots0logs Perfect, working! I set the URL in the `config.json` file to our real domain, that fixed the rest (as well as your commit). I don't think sharing my file is not very informative ;)

**Comment by lots0logs** [comment]
@ET-Bent Great! I'm glad you were able to resolve it :smile:

**Comment by bentalexanderhaase** [comment]
@lots0logs you resolved it ;)
