### ISSUE TITLE
Log out behaviour

### ISSUE THREAD

**Issue by jcano** [Antergos/nodebb-plugin-sso-auth0#3]
This is probably something I'm doing wrong. When using Auth0, if I log out the top navbar shows the login option again, so I'm assuming I'm correctly logged out. But when I try to log in again, I'm not shown the login screen, it just automatically logs me in as the last user I logged in as.

This doesn't  happen when I log out with a local user.

**Comment by lots0logs** [comment]
Let me know about this one as well :smiley:  Thanks!

**Comment by dhavaln** [comment]
@lots0logs  @jcano 
I am having the same issue.

We are using the NodeBB with Auth0 into one of our application, and NodeBB loads into the IFrame.

When we login to our main app via Auth0, and open the NodeBB Forums, it shows the correct user first time. But after logout and login back with different Auth0 user, the NodeBB still picks up the previously logged in user.

Logging out from Auth0 with - https://mydomain.auth0.com/v2/logout is not working as well.

Any idea ?
