### ISSUE TITLE
Deleting a user linked to Auth0

### ISSUE THREAD

**Issue by jcano** [Antergos/nodebb-plugin-sso-auth0#4]
After deleting on NodeBB control panel  a user that was created by logging in with Auth0, the behaviour is erratic.

If the user was marked as admin, when I try to log in again on Auth0 with that account after deleting it, NodeBB will sign me in with my main admin local account.

If the user was a normal user, NodeBB will sign me in as a guest and show 404s when trying to access the profile or settings.

In either case, the user is not shown on NodeBB's control panel.

**Comment by lots0logs** [comment]
Hi, sorry I missed your issue reports! Are you still having this issue? Please let me know. Thanks.
