### ISSUE TITLE
Save Button on Social Authentication setup not working

### ISSUE THREAD

**Issue by krisklosterman** [Antergos/nodebb-plugin-sso-auth0#5]
I enter my Auth0 data and try to use the material icon save button and it does nothing. No errors in console when visiting or pressing the button

**Comment by krisklosterman** [comment]
After re-installing 3 times, it started to work

**Comment by lots0logs** [comment]
Hmm..that's strange. I'll look into it just in case there is really a bug somewhere :smiley:

**Comment by krisklosterman** [comment]
Clarification: When I said re-install, I meant re-install the plugin 3 times, not NodeBB
