### ISSUE TITLE
Using LOCK to login into facebook error

### ISSUE THREAD

**Issue by krisklosterman** [Antergos/nodebb-plugin-sso-auth0#6]
When attempting to register with facebook and then using it to login through Auth0 Lock I get the following error, so do all other users. Using google to login works.

![Image of error](http://au-fait.net/errorMessage.png)

Nothing in Javascript log.

Here is the information in the log/output.log file ( I replaced data that might be sensitive with hidden)

AUTH0 ERROR - ENO-010: {"profile":{"provider":"facebook","displayName":"Kris Klosterman","id":"facebook|hidden","name":{"familyName":"Klosterman","givenName":"Kris"},"picture":"hidden?oh=hidden&oe=hidden","locale":"en_US","nickname":"Kris Klosterman","gender":"male","identities":[{"provider":"facebook","user_id":"hidden","connection":"facebook","isSocial":true}],"_json":{"name":"Kris Klosterman","given_name":"Kris","family_name":"Klosterman","gender":"male","picture":"hidden","picture_large":"hidden","age_range":{"min":21},"context":{"mutual_likes":{"data":[],"summary":{"total_count":100}},"id":"hidden"},"cover":{"id":"hidden","offset_y":0,"source":"hidden"},"devices":[{"os":"Android"}],"updated_time":"2016-09-04T22:08:13+0000","installed":true,"is_verified":false,"link":"hidden","locale":"en_US","name_format":"{first} {last}","timezone":-5,"third_party_id":"hidden","verified":true,"email_verified":true,"clientID":"hidden","updated_at":"2016-12-11T15:13:41.820Z","user_id":"facebook|hidden","nickname":"Kris Klosterman","identities":[{"provider":"facebook","user_id":"hidden","connection":"facebook","isSocial":true}],"created_at":"2016-12-11T14:28:20.972Z","sub":"facebook|hidden"},"_raw":"{\"name\":\"Kris Klosterman\",\"given_name\":\"Kris\",\"family_name\":\"Klosterman\",\"gender\":\"male\",\"picture\":\"hidden",\"picture_large\":\"hidden",\"age_range\":{\"min\":21},\"context\":{\"mutual_likes\":{\"data\":[],\"summary\":{\"total_count\":100}},\"id\":\"hidden\"},\"cover\":{\"id\":\"hidden\",\"offset_y\":0,\"source\":\"hidden"},\"devices\":[{\"os\":\"Android\"}],\"updated_time\":\"2016-09-04T22:08:13+0000\",\"installed\":true,\"is_verified\":false,\"link\":\"hidden",\"locale\":\"en_US\",\"name_format\":\"{first} {last}\",\"timezone\":-5,\"third_party_id\":\"hidden\",\"verified\":true,\"email_verified\":true,\"clientID\":\"hidden\",\"updated_at\":\"2016-12-11T15:13:41.820Z\",\"user_id\":\"facebook|hidden\",\"nickname\":\"Kris Klosterman\",\"identities\":[{\"provider\":\"facebook\",\"user_id\":\"hidden\",\"connection\":\"facebook\",\"isSocial\":true}],\"created_at\":\"2016-12-11T14:28:20.972Z\",\"sub\":\"facebook|hidden\"}"}}

11/12 10:13 [14937] - error: /auth/auth0/callback

**Comment by lots0logs** [comment]
Hey, check your Facebook app settings in Auth0 and make sure that the `email` field is selected under **Attributes**. Let me know if that resolves the issue. Thanks.

**Comment by krisklosterman** [comment]
That seemed to work, thanks!
