### ISSUE TITLE
When activating in nodebb 1.2.1, error: [plugins] filter:auth.init,  undefined

### ISSUE THREAD

**Issue by bret-2600** [Antergos/nodebb-plugin-sso-auth0#7]
Hello!  I'm not sure which versions this plug-in supports, but in 1.2.1, the following error occurs after restarting NodeBB after activating it.

16/12 18:51 [9433] - error: [plugins] filter:auth.init,  undefined
16/12 18:51 [9433] - error: filter:auth.init - plugin failure

Any help would be much appreciated.

**Comment by lots0logs** [comment]
Is that the only output related to the plugin? Have you filled in the plugin's settings?

**Comment by bret-2600** [comment]
Hi!  Thanks for your reply.  I didn't fill in the plugin's settings.  Where do I do that?

**Comment by lots0logs** [comment]
Its located in the admin under "Social Authentication".

**Comment by bret-2600** [comment]
Hmm.  I couldn't find any "Social Authentication" section.  When menu is that supposed to be under?  Does it show up only -after- installing your plug-in?  I tried activating the plug-in, then restarting nodebb from the admin dashboard, but still the Social Authentication was nowhere to be found.  Of course, I can't really log out of the admin panel and log in again, because without configuration, I can't be authenticated.  Ha ha ha.

Could it be that my NodeBB is a little outdated?  According to the dashboard, we're running 1.2.1.

Thanks!!

**Comment by lots0logs** [comment]
> Could it be that my NodeBB is a little outdated? According to the dashboard, we're running 1.2.1.

Nah, we're still running 1.1.2 ourselves :sweat_smile: 

Hmm.. :thinking: let me look into it and I'll get back to you asap.

**Comment by lots0logs** [comment]
Could you try installing the plugin manually using npm and let me know if any dependency problems show up?

**Comment by bret-2600** [comment]
I didn't see any strange output during the npm install.  Here's what it output:

nodebb@1.2.1 /var/www/html/forum/nodebb
└─┬ nodebb-plugin-sso-auth0@1.0.13 
  ├─┬ auth0-lock@10.8.1 
  │ ├── auth0-js@7.6.1 
  │ ├─┬ jsonp@0.2.1
  │ │ └── debug@2.6.0 
  │ ├─┬ react@15.4.1
  │ │ └─┬ fbjs@0.8.8 
  │ │   └── setimmediate@1.0.5 
  │ └─┬ react-dom@15.4.1
  │   └── fbjs@0.8.8 
  └─┬ passport-auth0@0.5.2
    └─┬ passport-oauth@1.0.0
      ├─┬ passport-oauth1@1.1.0
      │ └── oauth@0.9.15 
      └── passport-oauth2@1.4.0 


I'm still not sure where the Social Login menu item should appear once it does.  I checked all of the admin primary nav menus and it's not there.  I've double-checked and the plugin is "active" in the /admin/extend/plugins menu.

Thanks!

**Comment by lots0logs** [comment]
"Social Authentication" should be a top-level menu item. If its not then its probably due to a change in newer versions of NodeBB. I should have some time this weekend to look into it and fix it :smiley:

**Comment by bret-2600** [comment]
I upgraded our NodeBB to the newest version, 1.4.2.  When restarting NodeBB after activating the plugin, I still am getting:

```
9/1 19:08:03 [8031] - info: Time: Mon Jan 09 2017 19:08:03 GMT+0000 (UTC)
9/1 19:08:03 [8031] - info: Initializing NodeBB v1.4.2
9/1 19:08:04 [8031] - info: initializing NodeBB ...
9/1 19:08:05 [8031] - error: [plugins] filter:auth.init,  undefined
9/1 19:08:05 [8031] - error: filter:auth.init - plugin failure
9/1 19:08:05 [8031] - error: AUTH0 ERROR: id, secret, and domain are required.
9/1 19:08:05 [8031] - info: NodeBB Ready
9/1 19:08:05 [8031] - info: Enabling 'trust proxy'
9/1 19:08:05 [8031] - info: NodeBB is now listening on: 0.0.0.0:4567
```
The plugin appears to be saying, "I can't run because I'm not configured."  But doesn't the Social Authentication menu item not appear until the plugin is installed?  Isn't that a catch-22?  I'm probably misunderstanding part of the installation process.

**Comment by dhavaln** [comment]
@lots0logs 
Was this ever resolved ? I am using NodeBB 1.5.x, Node 7.10.x and latest version of the plugin but still same error.

```
error: [plugins] filter:auth.init,  undefined
error: An error has occurred. Please report this error to us and include the 
				following error code in your report: ENO-011b.
```

Also after the error, server crashes and I have to remove the plugin to start it again.

**Comment by lots0logs** [comment]
@dhavaln It should be resolved with the latest version of the plugin. Are you able to access the admin to configure the plugin settings or does it just crash right away when nodebb starts?

**Comment by dhavaln** [comment]
It crashes right after the plugin is activated and NodeBB is reloaded. However I could make it work based on this [commit](https://github.com/Antergos/nodebb-plugin-sso-auth0/blob/792a7bbdc6e99fc4b7ddee30c66a946f8b975ffd/library.js).

**Comment by lots0logs** [comment]
That is from before the ES6 rewrite. Hmm..looks like  this bug is back. I'll look into it asap.
