### ISSUE TITLE
Failed to lookup view "admin/plugins/sso-auth0" in views directory

### ISSUE THREAD

**Issue by olegberman** [Antergos/nodebb-plugin-sso-auth0#9]
```Failed to lookup view "admin/plugins/sso-auth0" in views directory "/Users/berman/Documents/StudyHub/NodeBB/build/public/templates"```

Big thank you for the plugin! 

For some reason I am getting this error when I am trying to go to `admin/plugins/sso-auth0` route. Would you have any idea why or what I am doing wrong?

Thanks

**Comment by lots0logs** [comment]
Hmm..I'm not sure. I haven't seen that error happen before TBH. Which version of NodeBB are you using? Which version of Node? Do you see any errors in the console when trying to access the endpoint?

**Comment by olegberman** [comment]
NodeBB 1.5.1
Node 7.10.0

I see this message in logs on startup, but that sholud be ok: ```[Auth0 SSO]: Before you can use this plugin, you must configure it. You can access the settings in the Social Authentication menu.```

No errors on plugin init when NodeBB starts, the menu item Social Authentication is there, Auth0 drop down item is there too... but when you click on it there's an error in the browser console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
acp.min.js?v=63ovr3avc7c:1 Uncaught Error: Unable to load template: admin/plugins/sso-auth0 (Not Found)
    at Object.error (acp.min.js?v=63ovr3avc7c:1)
    at l (acp.min.js?v=63ovr3avc7c:1)
    at Object.fireWith [as rejectWith] (acp.min.js?v=63ovr3avc7c:1)
    at C (acp.min.js?v=63ovr3avc7c:1)
    at XMLHttpRequest.<anonymous> (acp.min.js?v=63ovr3avc7c:1)
```

When I try to go directly to `admin/plugins/sso-auth0` I see that error and in my logs there is
```
16/6 10:32:31 [33698] - error: /admin/plugins/sso-auth0
 Error: Failed to lookup view "admin/plugins/sso-auth0" in views directory "/Users/berman/Documents/StudyHub/NodeBB/build/public/templates"
    at Function.render (/Users/berman/Documents/StudyHub/NodeBB/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/Users/berman/Documents/StudyHub/NodeBB/node_modules/express/lib/response.js:971:7)
    at content (/Users/berman/Documents/StudyHub/NodeBB/src/middleware/render.js:70:15)
etc...
```

**Comment by olegberman** [comment]
What is the version of NodeBB that you're running yourself? I will try it as well.

**Comment by olegberman** [comment]
I solved it - it wasn't enough to just restart NodeBB. I also had to also run `./nodebb build`. I am new to NodeBB and don't know if that's normal or not (should this be done after each plugin installed?).

Somebody has a similar issue here: https://community.nodebb.org/topic/9971/plugin-failed-to-lookup-view-on-nodebb-1-4-0-release

**Comment by lots0logs** [comment]
@olegberman Hmmm that is odd. The templates are rebuilt when you restart NodeBB so there should be no need to manually run the build command. Sounds like a bug to me. Might want to report it to NodeBB devs. Anyway, glad its working for you now. Cheers!
